---
- name: pull image
  docker_image:
    name: nextcloud/all-in-one:latest
    source: pull

- name: run a container
  docker_container:
    name: nextcloud-aio-mastercontainer
    image: mtabishk/ansible-container-node
    state: started
    restart: yes
    ports:
      - "80:80"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "nextcloud_aio_mastercontainer:/mnt/docker-aio-config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    jump: ACCEPT

- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: "8443"
    jump: ACCEPT

- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: "8080"
    jump: ACCEPT