---
- name: install plasma desktop
  apt:  
    name: 
      - kde-plasma-desktop
      - plasma-workspace-wayland  
    state: latest
    
- name: install extra kde apps
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ kde_apps }}"

- name: add volian repo gpg key
  apt_key: 
    state: present
    keyring: /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg
    url: https://deb.volian.org/volian/scar.key

- name: add volian repo
  apt_repository: 
    state: present
    filename: /etc/apt/sources.list.d/volian-archive-scar-unstable
    repo: "deb http://deb.volian.org/volian/ scar main"

- name: install bismuth
  apt:  
    name: 
      - kwin-bismuth
    state: latest

- name: add main user to additional groups 
  user:
    name: "{{ user }}"
    groups: 
      - audio
      - video
      - games 
      - input
    append: yes
    create_home: no

- name: enable profile sync daemon service for main user
  ignore_errors: yes
  become: yes
  become_user: "{{ user }}"
  systemd:
    name: psd.service
    enabled: yes
    scope: user

- name: create flatpak datasets
  when: ansible_group == zfs
  include_tasks: zfs-flatpak-datasets.yaml

- name: add the flathub flatpak repository remote to system
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: add flatpaks to system
  community.general.flatpak:
    state: present
    remote: flathub
    method: system
    name: "{{ item }}"
  loop: "{{ flatpak_apps }}"  

- name: create .config directory
  file:
    path: "/home/{{ user }}/.config"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '751'

- name: create .local directory
  file:
    path: "/home/{{ user }}/.local"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '751'

- name: copy kwinrc config file
  copy:
    src: "../files/.config"
    dest: "/home/{{ user }}/config"
    owner: "{{ user }}"
    group: users
    mode: '600'

- name: copy kwinrc config file
  copy:
    src: "../files/.config/kwinrc"
    dest: "/home/{{ user }}/.config/kwinrc"
    owner: "{{ user }}"
    group: users
    mode: '600'

- name: pull gebaar gestures repo
  git:
    clone: yes
    dest: "/home/{{ user }}/gebaar-libinput"
    repo: https://github.com/NICHOLAS85/gebaar-libinput
    recursive: yes
    update: yes

- name: "fix library dependancy for gebaar in cpptoml.h"
    lineinfile:
      path: "/home/{{ user }}/gebaar-libinput/libs/cpptoml/include/cpptoml.h"
      insertafter: "^#include"
      line: "#include <limits>"
      state: present

- name: "fix library dependancy for gebaar in cxxopts.hpp"
    lineinfile:
      path: "/home/{{ user }}/gebaar-libinput/libs/cxxopts/include/cxxopts.hpp"
      insertafter: "^#include"
      line: "#include <limits>"
      state: present

- name: create gebaar build directory
  file:
    path: "/home/{{ user }}/gebaar-libinput/build"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '751'


    #cd /home/$USER/gebaar-libinput-fork/build && cmake .. && make -j$(nproc)

    #mkdir -p $TEMPMOUNT/home/$USER/.config/gebaar

    #cp $CONFIGDIR/home/.config/autostart/gebaard.desktop $TEMPMOUNT/home/$USER/.config/autostart

    #echo "Run 'make install' from ~/gebaar-libinput-fork/build on boot"

