---
- name: create zfs datasets
  when: zfs_root|bool == true
  block:
    - name: create zfs user datasets
      community.general.zfs:
        name: "zroot/DATA/home/{{ user }}/{{ item }}"
        state: present
        extra_zfs_properties:
          canmount: on
          mountpoint: "/home/{{ user }}/{{ item }}"
      loop: "{{ zfs_user_datasets }}"

    - name: create zfs flatpak datasets
      community.general.zfs:
        name: "zroot/DATA/home/{{ user }}/{{ item }}"
        state: present
        extra_zfs_properties:
          canmount: on
          mountpoint: "/home/{{ user }}/{{ item }}"
      loop: "{{ zfs_flatpak_datasets }}"

    - name: create zfs extra datasets
      community.general.zfs:
        name: "zroot/DATA/home/{{ user }}/{{ item }}"
        state: present
        extra_zfs_properties:
          canmount: on
          mountpoint: "/home/{{ user }}/{{ item }}"
      loop: "{{ zfs_extra_datasets }}"

- name: create directories or fix ownership on user zfs datasets
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '755'
  loop: "{{ zfs_user_datasets }}"

- name: create directories or fix ownership on flatpak zfs datasets
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '755'
  loop: "{{ zfs_flatpak_datasets }}"

- name: create directories or fix ownership on extra zfs datasets
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '755'
  loop: "{{ zfs_extra_datasets }}"

- name: install plasma desktop
  apt:  
    name: 
      - kde-plasma-desktop
      - plasma-workspace-wayland  
    state: latest
    
- name: install extra kde apps
  apt:
    name: "{{ kde_apps }}"
    state: latest

- name: install extra desktop apps
  apt:
    name: "{{ desktop_apps }}"
    state: latest

- name: add volian repo gpg key
  apt_key: 
    state: present
    keyring: /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg
    url: https://deb.volian.org/volian/scar.key

- name: add volian repo
  apt_repository: 
    state: present
    filename: /etc/apt/sources.list.d/volian-archive-scar-unstable
    repo: "deb http://deb.volian.org/volian/ scar main"

- name: install bismuth
  apt:  
    name: 
      - kwin-bismuth
    state: latest

- name: add main user to additional groups 
  user:
    name: "{{ user }}"
    groups: 
      - audio
      - video
      - games 
      - input
    append: yes
    create_home: no

- name: setup package architecture config file
  lineinfile: 
    state: present
    create: yes
    dest: "/var/lib/dpkg/arch"
    regexp: "amd64"
    line: "amd64"

- name: setup architecture for games
  lineinfile: 
    state: present
    create: yes
    dest: "/var/lib/dpkg/arch"
    regexp: "i386"
    line: "i386"

- name: update repositories
  apt: 
    update_cache: yes
    upgrade: safe
  changed_when: False

- name: accept steam license
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"

- name: install game packages
  apt:
    name: "{{ game_apps }}"
    state: latest

- name: touchscreen configurations 
  when: touchscreen|bool == true
  block:
    - name: install touchscreen packages
      apt:
        name: "{{ touchscreen_apps }}"
        state: latest
    
    - name: configure firefox touch scrolling
      lineinfile: 
        state: present
        path: "/etc/security/pam_env.conf"
        regexp: 'MOZ_USE_XINPUT2 DEFAULT=1'
        line: 'MOZ_USE_XINPUT2 DEFAULT=1'
    
    - name: configure sddm lockscreen keyboard
      lineinfile: 
        state: present
        create: yes
        path: "/etc/sddm.conf"
        regexp: '[General]'
        line: '[General]'    
    
    - name: configure firefox touch scrolling
      lineinfile: 
        state: present
        path: "/etc/sddm.conf"
        regexp: 'InputMethod=qtvirtualkeyboard'
        line: 'InputMethod=qtvirtualkeyboard'

- name: add the flathub flatpak repository remote to system
  become_user: "{{ user }}"
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: add flatpaks to system
  become_user: "{{ user }}"
  community.general.flatpak:
    state: present
    remote: flathub
    method: user
    name: "{{ item }}"
  loop: "{{ flatpak_apps }}"

- name: create systemd user mode directories
  file:
    path: "/home/{{ user }}/.config/systemd/user/default.target.wants"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '751'

- name: enable profile sync daemon service for main user
  file:
    src: /usr/lib/systemd/user/psd.service
    path: "/home/{{ user }}/.config/systemd/user/default.target.wants/psd.service"
    state: link
    owner: "{{ user }}"
    group: users

- name: copy .local/share/plasma directory
  copy:
    src: "../files/plasma/.local/share/plasma"
    dest: "/home/{{ user }}/.local/share"
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy .local/share/aurorae directory
  copy:
    src: "../files/plasma/.local/share/aurorae"
    dest: "/home/{{ user }}/.local/share"
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy .local/share/color-schemes directory
  copy:
    src: "../files/plasma/.local/share/color-schemes"
    dest: "/home/{{ user }}/.local/share"
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy .local/share/konsole directory
  copy:
    src: "../files/plasma/.local/share/konsole"
    dest: "/home/{{ user }}/.local/share"
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy wallpaper
  copy:
    src: "../files/wallpaper/contents"
    dest: "/usr/share/wallpapers/Next"
    mode: '755'

- name: create .config directory
  file:
    path: "/home/{{ user }}/.config"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy .config/gtk-3.0 directory
  copy:
    src: "../files/plasma/.config/gtk-3.0"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy .config/gtk-4.0 directory
  copy:
    src: "../files/plasma/.config/gtk-4.0"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy .config/xsettingsd directory
  copy:
    src: "../files/plasma/.config/xsettingsd"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy .config/kdeglobals file
  copy:
    src: "../files/plasma/.config/kdeglobals"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/kglobalshortcutsrc file
  copy:
    src: "../files/plasma/.config/kglobalshortcutsrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/khotkeysrc file
  copy:
    src: "../files/plasma/.config/khotkeysrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/kscreenlockerrc file
  copy:
    src: "../files/plasma/.config/kscreenlockerrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/ksmserverrc file
  copy:
    src: "../files/plasma/.config/ksmserverrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/kwinrc file
  copy:
    src: "../files/plasma/.config/kwinrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/Trolltech.conf file
  copy:
    src: "../files/plasma/.config/Trolltech.conf"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/plasma-org.kde.plasma.desktop-appletsrc file
  copy:
    src: "../files/plasma/.config/plasma-org.kde.plasma.desktop-appletsrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/plasmarc file
  copy:
    src: "../files/plasma/.config/plasmarc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/plasmashellrc file
  copy:
    src: "../files/plasma/.config/plasmashellrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/klaunchrc file
  copy:
    src: "../files/plasma/.config/klaunchrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .config/autostart directory
  copy:
    src: "../files/plasma/.config/autostart"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '755'

- name: copy .conkyrc2 file
  copy:
    src: "../files/.conkyrc2"
    dest: "/home/{{ user }}"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy kcminputrc.j2 template
  template:
    src: "../templates/kcminputrc.j2"
    dest: "/home/{{ user }}/.config/kcminputrc"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: copy .conkyrc.j2 template
  template:
    src: "../templates/.conkyrc.j2"
    dest: "/home/{{ user }}/.conkyrc"
    owner: "{{ user }}"
    group: users
    mode: '644'

- name: setup flatpak discovery in /etc/zsh/zprofile
  lineinfile:
    state: present
    path: "/etc/zsh/zprofile"
    regexp: 'emulate sh -c "source /etc/profile.d/flatpak.sh"'
    line: 'emulate sh -c "source /etc/profile.d/flatpak.sh"'

- name: setup konsolerc config file
  lineinfile: 
    state: present
    create: yes
    dest: "/home/{{ user }}/.config/konsolerc"
    owner: "{{ user }}"
    group: users
    mode: '644'
    regexp: '[Desktop Entry][$i]'
    line: '[Desktop Entry][$i]'

- name: setup konsolerc config file
  lineinfile: 
    state: present
    create: yes
    dest: "/home/{{ user }}/.config/konsolerc"
    owner: "{{ user }}"
    group: users
    mode: '644'
    regexp: 'DefaultProfile=Profile 1.profile'
    line: 'DefaultProfile=Profile 1.profile'

- name: setup powermanagementprofilesrc config file
  lineinfile: 
    state: present
    create: yes
    dest: "/home/{{ user }}/.config/powermanagementprofilesrc"
    owner: "{{ user }}"
    group: users
    mode: '644'
    regexp: '[AC][SuspendSession]'
    line: '[AC][SuspendSession]'

- name: setup powermanagementprofilesrc config file
  lineinfile: 
    state: present
    create: yes
    dest: "/home/{{ user }}/.config/powermanagementprofilesrc"
    owner: "{{ user }}"
    group: users
    mode: '644'
    regexp: 'idleTime=1800000'
    line: 'idleTime=1800000'

- name: setup powermanagementprofilesrc config file
  lineinfile: 
    state: present
    create: yes
    dest: "/home/{{ user }}/.config/powermanagementprofilesrc"
    owner: "{{ user }}"
    group: users
    mode: '644'
    regexp: 'suspendThenHibernate=false'
    line: 'suspendThenHibernate=false'

- name: setup powermanagementprofilesrc config file
  lineinfile: 
    state: present
    create: yes
    dest: "/home/{{ user }}/.config/powermanagementprofilesrc"
    owner: "{{ user }}"
    group: users
    mode: '644'
    regexp: 'suspendType=1'
    line: 'suspendType=1'

- name: setup conky2 autostart config file
  lineinfile: 
    state: present
    create: yes
    dest: "/home/{{ user }}/.config/autostart/conky2.desktop"
    owner: "{{ user }}"
    group: users
    mode: '755'
    regexp: '^Exec='
    line: "Exec=conky -c /home/{{ user }}/.conkyrc2 --daemonize --pause=1"

- name: remove old network configuration
  file:
    path: "/etc/network/interfaces.d"
    state: absent