---
- name: create zfs datasets
  when: zfs_root|bool == true
  block:
    - name: create zfs user datasets
      community.general.zfs:
        name: "zroot/DATA/home/{{ user }}/{{ item }}"
        state: present
        extra_zfs_properties:
          canmount: on
          mountpoint: "/home/{{ user }}/{{ item }}"
      loop: "{{ zfs_user_datasets }}"

- name: create directories or fix ownership on user zfs datasets
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '750'
  loop: "{{ zfs_user_datasets }}"

- name: install plasma desktop
  apt:  
    name: "{{ kde_apps }}"
    state: latest

- name: add volian repo gpg key
  apt_key: 
    state: present
    keyring: /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg
    url: https://deb.volian.org/volian/scar.key

- name: add volian repo
  apt_repository: 
    state: present
    filename: /etc/apt/sources.list.d/volian-archive-scar-unstable
    repo: "deb http://deb.volian.org/volian/ scar main"

- name: install bismuth
  apt:  
    name: 
      - kwin-bismuth
    state: latest

- name: copy .local/share/plasma directory
  copy:
    src: "../files/plasma/.local/share/plasma"
    dest: "/home/{{ user }}/.local/share"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy .local/share/aurorae directory
  copy:
    src: "../files/plasma/.local/share/aurorae"
    dest: "/home/{{ user }}/.local/share"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy .local/share/color-schemes directory
  copy:
    src: "../files/plasma/.local/share/color-schemes"
    dest: "/home/{{ user }}/.local/share"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy .local/share/konsole directory
  copy:
    src: "../files/plasma/.local/share/konsole"
    dest: "/home/{{ user }}/.local/share"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy wallpaper
  copy:
    src: "../files/wallpaper/contents"
    dest: "/usr/share/wallpapers/Next"
    mode: '755'

- name: copy .config/gtk-3.0 directory
  copy:
    src: "../files/plasma/.config/gtk-3.0"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy .config/gtk-4.0 directory
  copy:
    src: "../files/plasma/.config/gtk-4.0"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy .config/xsettingsd directory
  copy:
    src: "../files/plasma/.config/xsettingsd"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy .config/kdeglobals file
  copy:
    src: "../files/plasma/.config/kdeglobals"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/kglobalshortcutsrc file
  copy:
    src: "../files/plasma/.config/kglobalshortcutsrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/khotkeysrc file
  copy:
    src: "../files/plasma/.config/khotkeysrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/kscreenlockerrc file
  copy:
    src: "../files/plasma/.config/kscreenlockerrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/ksmserverrc file
  copy:
    src: "../files/plasma/.config/ksmserverrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/kwinrc file
  copy:
    src: "../files/plasma/.config/kwinrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/Trolltech.conf file
  copy:
    src: "../files/plasma/.config/Trolltech.conf"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/plasma-org.kde.plasma.desktop-appletsrc file
  copy:
    src: "../files/plasma/.config/plasma-org.kde.plasma.desktop-appletsrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/plasmarc file
  copy:
    src: "../files/plasma/.config/plasmarc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/plasmashellrc file
  copy:
    src: "../files/plasma/.config/plasmashellrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/klaunchrc file
  copy:
    src: "../files/plasma/.config/klaunchrc"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: copy .config/autostart directory
  copy:
    src: "../files/plasma/.config/autostart"
    dest: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy kcminputrc.j2 template
  template:
    src: "../templates/kcminputrc.j2"
    dest: "/home/{{ user }}/.config/kcminputrc"
    owner: "{{ user }}"
    group: users
    mode: '640'

- name: "setup terminal profile"
  block:
    - lineinfile: 
        state: present
        create: yes
        path: "/home/{{ user }}/.config/konsolerc"
        regexp: '[Desktop Entry]'
        line: '[Desktop Entry]'  
        owner: "{{ user }}"
        group: users
        mode: '640'  
  
    - lineinfile: 
        state: present
        path: "/home/{{ user }}/.config/konsolerc"
        regexp: 'DefaultProfile=Profile 1.profile'
        line: 'DefaultProfile=Profile 1.profile'

- name: "touchscreen configuration: enable sddm lockscreen keyboard"
  when: touchscreen|bool == true
  block:
    - lineinfile: 
        state: present
        create: yes
        path: "/etc/sddm.conf"
        regexp: '[General]'
        line: '[General]' 
        owner: "{{ user }}"
        group: users
        mode: '640'   
  
    - lineinfile: 
        state: present
        path: "/etc/sddm.conf"
        regexp: 'InputMethod=qtvirtualkeyboard'
        line: 'InputMethod=qtvirtualkeyboard'
