---
- name: flatpak parent dataset
  community.general.zfs:
    name: 
      - "zroot/DATA/home/{{ user }}/.local/share/flatpak"
    state: present
    extra_zfs_properties:
      canmount: on
      mountpoint: "/home/{{ user }}/.local/share/flatpak"

- name: flatpak children datasets
  community.general.zfs:
    name: 
      - "zroot/DATA/home/{{ user }}/.local/share/flatpak/appstream"
    state: present
    extra_zfs_properties:
      canmount: on
      mountpoint: "/home/{{ user }}/.local/share/flatpak/appstream"

- name: flatpak children datasets
  community.general.zfs:
    name: 
      - "zroot/DATA/home/{{ user }}/.local/share/flatpak/repo"
    state: present
    extra_zfs_properties:
      canmount: on
      mountpoint: "/home/{{ user }}/.local/share/flatpak/appstream"

- name: flatpak children datasets
  community.general.zfs:
    name: 
      - "zroot/DATA/home/{{ user }}/.local/share/flatpak/runtime"
    state: present
    extra_zfs_properties:
      canmount: on
      mountpoint: "/home/{{ user }}/.local/share/flatpak/runtime"


- name: flatpak children datasets
  community.general.zfs:
    name: 
      - "zroot/DATA/home/{{ user }}/.local/share/flatpak/app"
    state: present
    extra_zfs_properties:
      canmount: on
      mountpoint: "/home/{{ user }}/.local/share/flatpak/app"


- name: flatpak runtime datasets
  community.general.zfs:
    name: 
      - "zroot/DATA/home/{{ user }}/.local/share/flatpak/runtime/{{ item }}"
    state: present
    extra_zfs_properties:
      canmount: on
      mountpoint: "/home/{{ user }}/.local/share/flatpak/runtime/{{ item }}"
  loop: "{{ zfs_datasets_flatpak_runtimes }}"

- name: flatpak datasets
  community.general.zfs:
    name: 
      - "zroot/DATA/home/{{ user }}/.local/share/flatpak/app/{{ item }}"
    state: present
    extra_zfs_properties:
      canmount: on
      mountpoint: "/home/{{ user }}/.local/share/flatpak/app/{{ item }}"
  loop: "{{ zfs_datasets_flatpak_apps }}"
     