---
- name: install kde plasma desktop
  hosts: latitude-test
  become: true

  tasks:
       - name: install plasma desktop
         apt:  
          name: 
            - kde-plasma-desktop
            - plasma-workspace-wayland  
          state: latest
       - name: install extra kde apps
         apt:
          name:
            - network-manager 
            - plasma-nm
            - accountwizard 
            - acpid 
            - akonadi-backend-postgresql 
            - akonadi-server
            - debconf-kde-data
            - debconf-kde-helper 
            - kde-config-fcitx5 
            - kde-config-fcitx
            - kdeaccessibility 
            - kdepim-addons 
            - kdepim-runtime 
            - kdepim-themeeditors 
            - keyutils 
            - kio-ldap
            - kmag 
            - kmousetool 
            - kmouth 
            - konq-plugins 
            - korganizer 
            - pinentry-qt 
            - plasma-integration 
            - plasma-runners-addons 
            - plasma-wallpapers-addons 
            - plasma-widgets-addons 
            - powermgmt-base
            - qtgstreamer-plugins-qt5
            - plasma-discover-backend-flatpak 
            - okular-extra-backends 
            - libreoffice-plasma 
            - ark 
            - gwenview 
            - kcalc 
            - kmahjongg 
            - kmines 
            - krdc 
            - ksudoku 
            - kde-spectacle 
            - ksystemlog 
            - kate 
            - okular 
            - yakuake 
            - marble 
            - kdenlive 
            - kigo 
            - kompare 
            - krfb 
            - ktimer
            - plasma-widgets-addons
            - profile-sync-daemon
            - print-manager
            - cups-browsed
            - make
            - cmake
            - build-essential
            - libsystemd-dev
            - libinput-tools
            - libinput-dev
        
            #- node-typescript 
            #- npm
            #- powertop


       - name: pull gebaar gestures repo
         git:
           clone: yes
           dest: "/home/{{ user }}"
           repo: https://github.com/osleg/gebaar-libinput-fork

#        - name: pull bismuth repo
#          git:
#            clone: yes
#            dest: "/home/{{ user }}"
#            repo: https://github.com/osleg/gebaar-libinput-fork

# .config/kwinrc
#[Compositing]
#OpenGLIsUnsafe=false
#
#[Desktops]
#Id_1=0f8bbc08-1b7d-4c56-bc8d-99b673d14ed2
#Id_2=de599c8c-4de1-453e-b972-1e62357f8dce
#Number=2
#Rows=1
#
#[Effect-PresentWindows]
#BorderActivateAll=9
#
#[Plugins]
#blurEnabled=false
#overviewEnabled=true
#zoomEnabled=false
#
#[Windows]
#FocusPolicy=FocusFollowsMouse

            