---
- name: install kde plasma desktop
  hosts: latitude-test
  become: true

  tasks:
       - name: install plasma desktop
         apt:  
          name: 
            - kde-plasma-desktop
            - plasma-workspace-wayland  
          state: latest
       
       - name: install extra kde apps
         apt:
          name:
            - network-manager 
            - plasma-nm
            - accountwizard 
            - acpid 
            - akonadi-backend-postgresql 
            - akonadi-server
            - debconf-kde-data
            - debconf-kde-helper 
            - kde-config-fcitx5 
            - kde-config-fcitx
            - kdeaccessibility 
            - kdepim-addons 
            - kdepim-runtime 
            - kdepim-themeeditors 
            - keyutils 
            - kio-ldap
            - kmag 
            - kmousetool 
            - kmouth 
            - konq-plugins 
            - korganizer 
            - pinentry-qt 
            - plasma-integration 
            - plasma-runners-addons 
            - plasma-wallpapers-addons 
            - plasma-widgets-addons 
            - powermgmt-base
            - qtgstreamer-plugins-qt5
            - plasma-discover-backend-flatpak 
            - okular-extra-backends 
            - libreoffice-plasma 
            - ark 
            - gwenview 
            - kcalc 
            - kmahjongg 
            - kmines 
            - krdc 
            - ksudoku 
            - kde-spectacle 
            - ksystemlog 
            - kate 
            - okular 
            - yakuake 
            - marble 
            - kdenlive 
            - kigo 
            - kompare 
            - krfb 
            - ktimer
            - plasma-widgets-addons
            - profile-sync-daemon
            - print-manager
            - cups-browsed
            - make
            - cmake
            - build-essential
            - libsystemd-dev
            - libinput-tools
            - libinput-dev

       - name: pull gebaar gestures repo
         git:
           clone: yes
           dest: "/home/{{ user }}/gebaar-libinput"
           repo: https://github.com/NICHOLAS85/gebaar-libinput
        
       - name: add volian repo gpg key
         apt_key: 
           state: present
           keyring: /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg
           url: https://deb.volian.org/volian/scar.key

       - name: add volian repo
         apt_repository: 
           state: present
           filename: /etc/apt/sources.list.d/volian-archive-scar-unstable
           repo: "deb http://deb.volian.org/volian/ scar main"
       
       - name: install bismuth
         apt:  
          name: 
            - kwin-bismuth
          state: latest

