---
- hosts: unconfigured_hosts
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-initialize

- hosts: latitude-test
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-base

# - hosts: corenet-node1
#   become: True
#   ignore_unreachable: True
#   roles:
#     - role: sm-proxmox-vms

# - name: qemu vm setup
#   hosts: 
#     - corenetworkmanagementvms
#     - corenetworkproductionvms
#   become: True
#   ignore_unreachable: True
#   roles:
#     - role: sm-vm

# - hosts: pxe-boot
#   become: True
#   ignore_unreachable: True
#   roles:
#     - role: sm-pxe

# - hosts: desktops
#   become: True
#   ignore_unreachable: True
#   roles:
#     - role: sm-kde
#     - role: desktop

# - hosts: surface-book2
#   become: True
#   ignore_unreachable: True
#   roles:
#     - role: sm-surface
