---
- hosts: all
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-initialize
    - role: geerlingguy.ntp

- hosts: corenetworkcluster
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-proxmox
    - role: lae.proxmox

- hosts: desktops
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-kde

- name: qemu vm setup
  hosts: 
    - corenetworkmanagementvms
    - corenetworkproductionvms
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-vm

- hosts: pxe-boot
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-pxe
    