---
- hosts: all
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-initialize

- hosts: corenetcluster
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-pre-proxmox
    - role: lae.proxmox
    - role: sm-post-proxmox

- name: qemu vm setup
  hosts: 
    - corenetworkmanagementvms
    - corenetworkproductionvms
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-initialize
    