---
- hosts: corenetcluster
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-initialize

- hosts: corenetcluster
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-pre-proxmox
    - role: lae.proxmox
    - role: sm-post-proxmox
    - role: sm-proxmox-vms

# - name: qemu vm setup
#   hosts: 
#     - corenetworkmanagementvms
#     - corenetworkproductionvms
#   become: True
#   ignore_unreachable: True
#   roles:
#     - role: sm-initialize
#     - role: sm-vm
    