---
- hosts: 
    - main-desktop
    - surface-book2
    - hp-tablet
    - latitude-test
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-initialize

- hosts:
    - main-desktop
    - surface-book2
    - hp-tablet
    - latitude-test
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-desktop