---
- hosts: 
    - hp-tablet
    - latitude-test
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-initialize

- hosts:
    - hp-tablet
    - latitude-test
  become: True
  ignore_unreachable: True
  roles:
    - role: sm-desktop