---
- name: "create pve dataset: zroot/DATA/var/lib/vz"
  when: zfs_root
  community.general.zfs:
    name: "zroot/DATA/var/lib/vz"
    state: present
    extra_zfs_properties:
        canmount: off

- name: "create pve dataset: zroot/DATA/var/lib/vz/dump"
  when: zfs_root
  community.general.zfs:
    name: "zroot/DATA/var/lib/vz/dump"
    state: present
    extra_zfs_properties:
        canmount: on
        mountpoint: /var/lib/vz/dump

- name: "create pve dataset: zroot/DATA/var/lib/vz/images"
  when: zfs_root
  community.general.zfs:
    name: "zroot/DATA/var/lib/vz/images"
    state: present
    extra_zfs_properties:
        canmount: on
        mountpoint: /var/lib/vz/images

- name: "create pve dataset: zroot/DATA/var/lib/vz/template"
  when: zfs_root
  community.general.zfs:
    name: "zroot/DATA/var/lib/vz/template"
    state: present
    extra_zfs_properties:
        canmount: on
        mountpoint: /var/lib/vz/template