# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

[ -n "$SSH_TTY" ] && [ -z "$TMUX"  ] && { tmux attach || exec tmux new-session;}
emulate sh -c "export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket"