---
- name: post ansible initialization
  hosts: pxeconfigured
  become: true
  
  tasks:
    - name: change hostname
      hostname:  
        name: "{{ new_hostname }}"
        use: systemd

    - name: update hosts file
      lineinfile: 
        state: present
        dest: /etc/hosts
        line: "127.0.1.1       {{ new_hostname }}.{{ ansible_dns.domain }} {{ new_hostname }}"
        regexp: "^127.0.1.1"

#    - include_task: "{{ root_of_repo }}/roles/sm-initialize/tasks/register-new-host.yaml"    
