---
- name: post install initialization
  hosts: all
  become: true
  ignore_unreachable: 
  host_key_checking: False
  
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes
        upgrade: safe
      changed_when: False
  
  tasks:
    - name: default packages
      apt:  
        name: "{{ item }}"
        state: latest
      loop: "{{ default_packages }}"

    - name: Copy zsh environment file
      copy:
        src: "../files/zshenv"
        dest: "/etc/zsh/"
        owner: root
        group: root
        mode: '644'
    
    - name: Copy zsh profile
      copy:
        src: "../files/zprofile"
        dest: "/etc/zsh/"
        owner: root
        group: root
        mode: '644'

    - name: create zfs dataset for standard user home directory
      when: zfs_root
      community.general.zfs:
        name: "zroot/DATA/home/{{ user }}"
        state: present
        extra_zfs_properties:
            canmount: on
            mountpoint: "/home/{{ user }}"

    - name: create standard user
      user:
        name: "{{ user }}"
        state: present
        shell: /bin/zsh
        uid: 1001
        group: users
        create_home: yes
        home: "/home/{{ user }}"
        groups: sudo
        append: yes
        
    - name: change user password
      user:
        name: "{{ user }}"
        update_password: always
        password: "{{ user_passwd |password_hash('sha512') }}"

    - name: fix permissions on user home directory
      file:
        path: "/home/{{ user }}"
        state: directory
        owner: "{{ user }}"
        group: users

    - name: Create .ssh directory
      file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: users
        mode: '751'
    
    - name: Copy ssh authorized_keys
      copy:
        src: "../files/authorized_keys"
        dest: "/home/{{ user }}/.ssh/"
        owner: "{{ user }}"
        group: users
        mode: '644'    

    - name: Copy zsh config
      copy:
        src: "../files/.zshrc"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'
    
    - name: Copy zsh-antigen config
      copy:
        remote_src: yes
        src: "/usr/share/zsh-antigen/antigen.zsh"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: Copy git config
      copy:
        src: "../files/.gitconfig"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: Copy vim config
      copy:
        src: "../files/.vimrc"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: change hostname
      hostname:  
        name: "{{ hostname }}"
        use: systemd

    - name: update hosts file
      lineinfile: 
        state: present
        dest: /etc/hosts
        line: "127.0.1.1       {{ hostname }}.{{ ansible_dns.domain }} {{ hostname }}"
        regexp: "^127.0.1.1"

    - name: change root password
      user:
        name: root
        update_password: always
        password: "{{ root_passwd |password_hash('sha512') }}"

    - name: change ansible user password
      user:
        name: "{{ ansible_user }}"
        update_password: always
        password: "{{ ansible_passwd |password_hash('sha512') }}"

    - name: change hostname
      hostname:  
        name: "{{ hostname }}"
        use: systemd

    - name: update hosts file
      lineinfile: 
        state: present
        dest: /etc/hosts
        line: "127.0.1.1       {{ hostname }}.{{ ansible_dns.domain }} {{ hostname }}"
        regexp: "^127.0.1.1"
