---
- name: change hostname
  hostname:  
    name: "{{ hostname }}"
    use: systemd

- name: update hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "\
      {# Match an IPv4/v6 address at the start #}\
      ^\\s*[0-9a-f:.]+\
      {# Match at least one whitespace, and any non-hostname names #}\
      (\\s+.*)*\\s\
      {# Match either our fqdn or hostname #}\
      (({{ ansible_hostname | regex_escape() }}|unconfigured-host).({{ domain | regex_escape() }}|managenet.lan)|({{ ansible_hostname | regex_escape() }}|unconfigured-host))\
      (\\s+.*)*\\s\
      (({{ ansible_hostname | regex_escape() }}|unconfigured-host).({{ domain | regex_escape() }}|managenet.lan)|({{ ansible_hostname | regex_escape() }}|unconfigured-host))\
      {# Require there be a word boundary at the end of the name(s). #}\
      {# This can be any whitespace, or end-of-line. #}\
      (\\s+.*|\\s*)$"
    line: "{{ ansible_default_ipv4.address }} {{ hostname }}.{{ domain }} {{ hostname }}"
    backup: yes
 
- name: change root password
  user:
    name: root
    update_password: always
    password: "{{ root_passwd |password_hash('sha512') }}"

- name: change ansible user password
  user:
    name: "{{ ansible_user }}"
    update_password: always
    password: "{{ ansible_passwd |password_hash('sha512') }}"