---
- name: update repositories
  apt: 
    update_cache: yes
    upgrade: safe
  changed_when: False
  
# - name: update hosts file
#   lineinfile: 
#     state: present
#     dest: /etc/hosts
#     line: "{{ ansible_default_ipv4.address }}       {{ hostname }}.{{ ansible_dns.domain }} {{ hostname }}"
#     regexp: "^127.0.1.1"

- name: Install bridge-utils
  apt:
    name: bridge-utils
    state: present

- name: Check if d folder is empty before proceeding
  stat:
    path: "/etc/network/interfaces.d/*"
  register: interfacesfound

- name: copy /etc/network/interfaces.j2 template
  template:
    src: "../templates/interfaces.j2"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: '644'
  when: interfacesfound.stat.exists #interfacesfound.stat.exists == True

- name: "remove interface configs in /etc/network/interfaces.d"
  file:
    path: "/etc/network/interfaces.d"
    state: absent

- name: create proxmox datasets
  when: zfs_root
  include_tasks: zfs-proxmox-datasets.yaml

- name: remove zfs dkms
  ignore_errors: yes
  apt:
    name:
      - zfs-dkms
    state: absent


