---
- name: update repositories
  apt: 
    update_cache: yes
    upgrade: safe
  changed_when: False

- name: Install bridge-utils
  apt:
    name: bridge-utils
    state: present

- name: Check if interfaces.d folder is empty before proceeding
  stat:
    path: "/etc/network/interfaces.d"
  register: interfacesdir

- name: copy /etc/network/interfaces.j2 template
  template:
    src: "../templates/interfaces.j2"
    dest: "/etc/network/interfaces"
    owner: root
    group: root
    mode: '644'
  when: interfacesdir.stat.exists

- name: "remove interface configs in /etc/network/interfaces.d"
  file:
    path: "/etc/network/interfaces.d"
    state: absent

- name: create proxmox datasets
  when: zfs_root|bool == true
  include_tasks: zfs-proxmox-datasets.yaml

- name: remove zfs dkms
  ignore_errors: yes
  apt:
    name: zfs-dkms
    state: absent

- name: set mailname for postfix
  debconf: 
    name: postifx
    question: postfix/mailname
    value: "{{ hostname }}.{{ ansible_domain }}"
    vtype: string

- name: set mailer type for postfix
  debconf: 
    name: postfix
    question: postfix/main_mailer_type
    value: "Local Only"
    vtype: string

- name: install postfix
  apt: 
    name: postfix
    state: present

