---
- name: docker packages
  apt:  
    name: 
      - docker.io
      - docker-compose
    state: latest

- name: Install docker daemon config for persistent logging
  copy:
    src: "../files/daemon.json"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Install rsyslog config for docker daemon persistent logging
  copy:
    src: "../files/49-docker-daemon.conf"
    dest: /etc/rsyslog.d/49-docker-daemon.conf
    owner: root
    group: root
    mode: '0644'

- name: Install rsyslog config for docker container persistent logging
  copy:
    src: "../files/48-docker-containers.conf"
    dest: /etc/rsyslog.d/48-docker-containers.conf
    owner: root
    group: root
    mode: '0644'

- name: Install docker log rotation config
  copy:
    src: "../files/docker"
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: '0644'

- name: Restart docker service
  systemd:
    name: docker.service
    enabled: yes
    state: restarted
