---
- name: docker setup
  hosts: docker
  become: true
  
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes
        upgrade: safe
      changed_when: False

  tasks:
    - name: docker packages
      apt:  
        name: 
          - docker.io
          - docker-compose
        state: latest

    - name: Install docker daemon config for persistent logging
      copy:
        src: "{{ root_of_repo }}/files/configs/docker/daemon.json"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'

    - name: Install rsyslog config for docker daemon persistent logging
      copy:
        src: "{{ root_of_repo }}/files/configs/docker/49-docker-daemon.conf"
        dest: /etc/rsyslog.d/49-docker-daemon.conf
        owner: root
        group: root
        mode: '0644'

    - name: Install rsyslog config for docker container persistent logging
      copy:
        src: "{{ root_of_repo }}/files/configs/docker/48-docker-containers.conf"
        dest: /etc/rsyslog.d/48-docker-containers.conf
        owner: root
        group: root
        mode: '0644'

    - name: Install docker log rotation config
      copy:
        src: "{{ root_of_repo }}/files/configs/docker/docker"
        dest: /etc/logrotate.d/docker
        owner: root
        group: root
        mode: '0644'

    - name: Restart docker service
      systemd:
        name: docker.service
        enabled: yes
        state: restarted