---
gnome_apps:
      - gnome
      - network-manager 
      - python3-psutil
      - gnome-shell-extension-prefs
      - gnome-shell-extension-manager
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-tiling-assistant
      - gnome-shell-extension-gpaste
      
zfs_user_datasets:
      - "Documents"
      - "Downloads"
      - "Music"
      - "Pictures"
      - "Videos"
      - "Games"
      - ".config"