---
- name: post pxe-boot initialization
  hosts: pxeconfigured
  become: true
  ignore_unreachable: yes
  
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes
        upgrade: safe
      changed_when: False
  
  tasks:
    - name: default packages
      apt:  
        name: 
          - vim
          - git
          - rsync
          - dosfstools
          - openssh-server
          - curl
          - wget
          - apt-file
          - software-properties-common
          - apt-transport-https
          - zsh
          - zsh-antigen
          - irssi
          - lynx
          - elinks
          - lm-sensors
          - net-tools
          - screen
          - tmux
          - sysstat
          - htop
          - iotop
          - ripgrep
          - nmap
          - iftop
          - tcpdump
          - smartmontools
        state: latest

    - name: update hosts file
      lineinfile: 
        state: present
        dest: /etc/zsh/zshenv
        line: '        export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"'
        regexp: "export"

    - name: create standard user
      user:
        name: "{{ user }}"
        state: present
        shell: /bin/zsh
        uid: 1001
        group: users
        create_home: yes
        home: "/home/{{ user }}"
        append: yes
        groups: sudo
        update_password: always
        password: "{{ user_passwd |password_hash('sha512') }}"

    - name: Copy zsh config
      copy:
        src: "{{ root_of_repo }}/files/configs/.zshrc"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'
    
    - name: Copy zsh config
      copy:
        remote_src: yes
        src: "/usr/share/zsh-antigen/antigen.zsh"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: Copy git config
      copy:
        src: "{{ root_of_repo }}/files/configs/.gitconfig"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: Copy vim config
      copy:
        src: "{{ root_of_repo }}/files/configs/.vimrc"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: change root password
      user:
        name: root
        update_password: always
        password: "{{ root_passwd |password_hash('sha512') }}"

    - name: change ansible user password
      user:
        name: "{{ ansible_user }}"
        update_password: always
        password: "{{ ansible_passwd |password_hash('sha512') }}"
