---
- name: post pxe-boot initialization
  hosts: unconfigured
  become: true
  ignore_unreachable: yes
  
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes
        upgrade: safe
      changed_when: False
  
  tasks:
    - name: default packages
      apt:  
        name: 
          - vim
          - git
          - rsync
          - dosfstools
          - openssh-server
          - curl
          - wget
          - apt-file
          - software-properties-common
          - apt-transport-https
          - zsh
          - zsh-antigen
          - irssi
          - lynx
          - elinks
          - lm-sensors
          - net-tools
          - screen
          - tmux
          - sysstat
          - htop
          - iotop
          - ripgrep
          - nmap
          - iftop
          - tcpdump
          - smartmontools
        state: latest

    - name: Copy zsh environment file
      copy:
        src: "{{ root_of_repo }}/files/configs/zshenv"
        dest: "/etc/zsh/"
        owner: root
        group: root
        mode: '644'
    
    - name: Copy zsh profile
      copy:
        src: "{{ root_of_repo }}/files/configs/zprofile"
        dest: "/etc/zsh/"
        owner: root
        group: root
        mode: '644'

    - name: create zfs dataset for standard user home directory 
      community.general.zfs:
        name: "zroot/DATA/home/{{ user }}"
        state: present
        extra_zfs_properties:
            canmount: on
            mountpoint: "/home/{{ user }}"

    - name: create standard user
      user:
        name: "{{ user }}"
        state: present
        shell: /bin/zsh
        uid: 1001
        group: users
        create_home: yes
        home: "/home/{{ user }}"
        groups: sudo
        update_password: always
        password: "{{ user_passwd |password_hash('sha512') }}"

    - name: Create .ssh directory
      file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: users
        mode: '751'
    
    - name: Copy ssh authorized_keys
      copy:
        src: "{{ root_of_repo }}/files/configs/user/authorized_keys"
        dest: "/home/{{ user }}/.ssh/"
        owner: "{{ user }}"
        group: users
        mode: '644'    

    - name: Copy zsh config
      copy:
        src: "{{ root_of_repo }}/files/configs/user/.zshrc"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'
    
    - name: Copy zsh-antigen config
      copy:
        remote_src: yes
        src: "/usr/share/zsh-antigen/antigen.zsh"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: Copy git config
      copy:
        src: "{{ root_of_repo }}/files/configs/user/.gitconfig"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: Copy vim config
      copy:
        src: "{{ root_of_repo }}/files/configs/user/.vimrc"
        dest: "/home/{{ user }}/"
        owner: "{{ user }}"
        group: users
        mode: '644'

    - name: change root password
      user:
        name: root
        update_password: always
        password: "{{ root_passwd |password_hash('sha512') }}"

    - name: change ansible user password
      user:
        name: "{{ ansible_user }}"
        update_password: always
        password: "{{ ansible_passwd |password_hash('sha512') }}"
