---
- name: stop and disable proxmox-boot-cleanup service
  systemd:
    name: proxmox-boot-cleanup.service
    enabled: no
    state: stopped

- name: "Comment out the line"
  replace:
    path: "{{ item }}"
    regexp: '^[^#]'
    replace: '#\g<0>'
  loop: "{{ filestopatch }}"

- name: "append successful exit"
  lineinfile:
    path: "{{ item }}"
    regexp: '^#exit 0'
    insertafter: EOF
    line: "exit 0"
  loop: "{{ filestopatch }}"

- name: remove uneeded debian-packages
  ignore_errors: yes
  apt:
    name: 
      - linux-image-amd64
      - linux-headers-amd64
      - grub-common
      - grub2-common
      - grub-pc
      - grub-pc-bin
      - os-prober
    state: absent