---
  tasks:
    - name: stop and disable proxmox-boot-cleanup service
      systemd:
        name: proxmox-boot-cleanup.service
        enabled: no
        state: stopped

    - name: "Comment out the line"
      replace:
        path: "{{ filestopatch }}"
        regexp: '^[^#]'
        replace: '#\1'

    - name: "append successful exit"
      lineinfile:
        path: "{{ filestopatch }}"
        regexp: '^#exit 0'
        insertafter: EOF

    # - block:
    #   - name: Reboot for new kernel
    #     shell: "sleep 5 && shutdown -r now 'Networking changes found, rebooting'"
    #     async: 1
    #     poll: 0

    #   - name: Wait for server to come back online
    #     wait_for_connection:
    #       delay: 15
    #     #when ... new kernel - first install

    # - name: remove uneeded debian-packages
    #   ignore_errors: yes
    #   apt:
    #     name: 
    #       - linux-image-amd64
    #       - linux-headers-amd64
    #       - grub-common
    #       - grub2-common
    #       - grub-pc
    #       - grub-pc-bin
    #       - os-prober
    #     state: absent