---
- name: copy in debian iso
  copy:
    src: "../files/debian-custom.iso"
    dest: "/var/lib/vz/template/iso/debian-custom.iso"
    owner: root
    group: root
    mode: '644'

- name: check if opnsense iso exists
  stat:
    path: "/var/lib/vz/template/iso/opnsense.iso"
  register: isopath

- name: copy in opnsense iso
  when: not isopath.stat.exists
  copy:
    src: "../files/opnsense.iso"
    dest: "/var/lib/vz/template/iso/opnsense.iso"
    owner: root
    group: root
    mode: '644'

- name: stop and disable proxmox-boot-cleanup service
  systemd:
    name: proxmox-boot-cleanup.service
    enabled: no
    state: stopped

- name: "Comment out the line"
  replace:
    path: "{{ item }}"
    regexp: '^[^#]'
    replace: '#\g<0>'
  loop: "{{ filestopatch }}"

- name: "append successful exit"
  lineinfile:
    path: "{{ item }}"
    regexp: '^#exit 0'
    insertafter: EOF
    line: "exit 0"
  loop: "{{ filestopatch }}"

- name: remove uneeded debian-packages
  ignore_errors: True
  apt:
    name: 
      - linux-image-amd64
      - linux-headers-amd64
      - grub-common
      - grub2-common
      - grub-pc
      - grub-pc-bin
      - os-prober
    state: absent