---
### Requires docker task

- name: pxe-boot setup
  hosts: pxe-boot
  become: true
  
  pre_tasks:
    - name: install and setup docker
      include: "{{ root_of_repo }}/roles/sm-docker/default/main.yaml"
  
  tasks:
    - name: pull compose files from pxe-boot repo
      git:
        clone: yes
        dest: /srv/pxe-boot
        repo: https://github.com/samuelmcpherson/pxe-boot.git






#    - name: install TFTP server
#      apt:  
#        name: 
#          - tftpd-hpa
#        state: latest

#    - name: Install default config
#      copy:
#        src: "{{ root_of_repo }}/files/pxe-tftp/tftpd-hpa"
#        dest: /etc/default/tftpd-hpa
#        owner: root
#        group: root
#        mode: '0644'

#    - name: Restart service
#      systemd:
#        name: tftpd-hpa.service
#        enabled: yes
#        state: restarted