---
- name: pxe-boot setup
  hosts: pxe
  become: true

  tasks:
    - name: install TFTP server
      apt:  
        name: 
          - tftpd-hpa
        state: latest

    - name: Install default config
      copy:
        src: files/pxe-tftp/tftpd-hpa
        dest: /etc/default/tftpd-hpa
        owner: root
        group: root
        mode: '0644'

    - name: Restart service
      systemd:
        name: 
          - tftpd-hpa.service
        enabled:
          - yes
        state:
          - restarted