---
### Requires docker task

- name: pxe-boot setup
  hosts: pxe-boot
  become: true
  
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes
        upgrade: safe
      changed_when: False
    
    - name: install and setup docker
      include_tasks: "{{ root_of_repo }}/roles/sm-docker/tasks/install-docker.yaml"
  
  tasks:
    - name: pull compose files from pxe-boot repo
      git:
        clone: yes
        dest: /srv/pxe-boot
        repo: https://github.com/samuelmcpherson/pxe-boot.git

    - name: start docker-compose stack for nginx container serving installer preseed
      docker_compose:
        project_src: /srv/pxe-boot/nginx-preseed
        state: present
        restarted: yes

    - name: start docker-compose stack for tftp container serving tftp pxe boot environment
      docker_compose:
        project_src: /srv/pxe-boot/tftp-pxe
        state: present
        restarted: yes
