---
### Requires docker task

- name: pxe-boot setup
  hosts: pxe-boot
  become: true
  
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes
        upgrade: safe
      changed_when: False
    
    - name: install and setup docker
      include_tasks: "{{ root_of_repo }}/roles/sm-docker/tasks/install-docker.yaml"
  
  tasks:
    - name: install iso build script dependencies
      apt:
        name:
          - debootstrap 
          - squashfs-tools 
          - xorriso 
          - isolinux 
          - syslinux-efi 
          - grub-pc-bin 
          - grub-efi-amd64-bin 
          - mtools
    
    - name: pull tftp compose stack from pxe-boot repo
      git:
        clone: yes
        update: yes
        dest: /srv/pxe-boot
        repo: https://github.com/samuelmcpherson/pxe-boot.git

    - name: pull iso build repo
      git:
        clone: yes
        update: yes
        dest: /root/debian-custom-iso
        repo: https://github.com/samuelmcpherson/debian-custom-iso.git

    - name: Clean up from previous build script runs
      file:
        path: /live-build
        state: absent

    - name: run custom iso build script
      command:
        cmd: "/root/debian-custom-iso/debian-build.sh /srv/pxe-boot/tftp-pxe/tftp/debian-installer/amd64 {{ root_passwd }}" 

    - name: start docker-compose stack for tftp container serving tftp pxe boot environment
      docker_compose:
        project_src: /srv/pxe-boot/tftp-pxe
        state: present
        restarted: yes
