---
- name: create zfs user datasets
  community.general.zfs:
    name: "zroot/DATA/home/{{ user }}/{{ item }}"
    state: present
    extra_zfs_properties:
      canmount: on
      mountpoint: "/home/{{ user }}/{{ item }}"
  loop: "{{ zfs_user_datasets }}"

- name: create directories or fix ownership on user zfs datasets
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '750'
  loop: "{{ zfs_user_datasets }}"

- name: install gnome desktop
  apt:  
    name: "{{ gnome_apps }}"
    state: latest

- name: create wallpaper directory
  file:
    path: "/home/{{ user }}/Pictures/wallpaper"
    state: directory
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: copy wallpaper
  copy:
    src: "../files/wallpaper/debian.jpg"
    dest: "/home/{{ user }}/Pictures/wallpaper/debian.jpg"
    owner: "{{ user }}"
    group: users
    mode: '750'

- name: 'setup window focus (follows mouse)'
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/focus-mode"
    value: "'sloppy'"
    state: present

- name: enable tap to click
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"
    state: present

- name: set sleep timeout to 15 minutes
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "900"
    state: present

- name: configure dark theme
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present

- name: configure terminal dark theme
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/theme-variant"
    value: "'dark'"
    state: present

- name: configure terminal profile background color 
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
    value: "'rgb(0,0,0)'"
    state: present

- name: configure terminal profile font color 
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
    value: "'rgb(255,255,255)'"
    state: present

- name: configure terminal profile colors 
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
    value: "false"
    state: present

- name: show battery percentage
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"
    state: present

- name: allow volume over 100
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
    value: "true"
    state: present

- name: disable automatic brightness
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled"
    value: "false"
    state: present

- name: limit window switching to one workspace
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"
    state: present

- name: set wallpaper
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/{{ user }}/Pictures/wallpaper/debian.jpg'"
    state: present

- name: set wallpaper
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///home/{{ user }}/Pictures/wallpaper/debian.jpg'"
    state: present

- name: set lockscreen picture
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///home/{{ user }}/Pictures/wallpaper/debian.jpg'"
    state: present

- name: set pinned applications
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'org.mozilla.firefox.desktop', 'com.github.Eloston.UngoogledChromium.desktop', 'im.riot.Riot.desktop', 'com.discordapp.Discord.desktop', 'org.telegram.desktop.desktop', 'us.zoom.Zoom.desktop', 'com.belmoussaoui.Authenticator.desktop', 'com.vscodium.codium.desktop', 'com.axosoft.GitKraken.desktop', 'com.jgraph.drawio.desktop.desktop', 'steam.desktop', 'calibre-gui.desktop', 'net.cozic.joplin_desktop.desktop', 'com.github.xournalpp.xournalpp.desktop']"
    state: present

- name: enable extensions
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['GPaste@gnome-shell-extensions.gnome.org', 'caffeine@patapon.info', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'tiling-assistant@leleat-on-github', 'window-list@gnome-shell-extensions.gcampax.github.com', 'windowsNavigator@gnome-shell-extensions.gcampax.github.com']"
    state: present

- name: configure window grouping for window list extension
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/window-list/grouping-mode"
    value: "'auto'"
    state: present

- name: enable on screen keyboard
  when: touchscreen|bool == true
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/desktop/a11y/applications/screen-keyboard-enabled"
    value: "true"
    state: present
