---
kde_apps:
      - network-manager 
      - plasma-nm
      - accountwizard 
      - acpid 
      - akonadi-backend-postgresql 
      - akonadi-server
      - debconf-kde-data
      - debconf-kde-helper 
      - kde-config-fcitx5 
      - kde-config-fcitx
      - kdeaccessibility 
      - kdepim-addons 
      - kdepim-runtime 
      - kdepim-themeeditors 
      - keyutils 
      - kio-ldap
      - kmag 
      - kmousetool 
      - kmouth 
      - konq-plugins 
      - korganizer 
      - pinentry-qt 
      - plasma-integration 
      - plasma-runners-addons 
      - plasma-wallpapers-addons 
      - plasma-widgets-addons 
      - powermgmt-base
      - qtgstreamer-plugins-qt5
      - plasma-discover-backend-flatpak 
      - okular-extra-backends 
      - libreoffice-plasma 
      - ark 
      - gwenview 
      - kcalc 
      - kmahjongg 
      - kmines 
      - krdc 
      - ksudoku 
      - kde-spectacle 
      - ksystemlog 
      - kate 
      - okular 
      - yakuake 
      - marble 
      - kdenlive 
      - kigo 
      - kompare 
      - krfb 
      - ktimer
      - plasma-widgets-addons
      - profile-sync-daemon
      - print-manager
      - cups-browsed
      - make
      - cmake
      - build-essential
      - libsystemd-dev
      - libinput-tools
      - libinput-dev
      - conky-all
      - gimp
      - hugo
      - texlive-base
      - texlive-bibtex-extra
      - texlive-fonts-extra
      - texlive-latex-base-doc
      - texlive-latex-base
      - texlive-latex-extra-doc
      - texlive-latex-extra
      - calibre

game_apps:
      - libglx-mesa0:i386 
      - mesa-vulkan-drivers:i386 
      - libgl1-mesa-dri:i386
      - lutris
      - steam 

flatpak_apps:
      - app/com.github.tchx84.Flatseal
      - app/com.github.eloston.ungoogledchromium
      - app/org.mozilla.firefox
      - app/com.vscodium.codium
      - app/com.jgraph.drawio.desktop
      - app/com.discordapp.discord
      - app/com.github.xournalpp.xournalpp
      - app/us.zoom.zoom
      - app/com.axosoft.gitkraken
      - app/com.belmoussaoui.Authenticator
      - app/net.cozic.joplin_desktop
      - app/net.davidotek.pupgui2

zfs_datasets_flatpak_runtimes:
      - "org.freedesktop.Platform.GL.default"
      - "org.freedesktop.Platform.VAAPI.Intel"
      - "org.freedesktop.Platform.openh264"
      - "org.gnome.Platform.Locale"
      - "org.gnome.Platform"
      - "com.github.Eloston.UngoogledChromium.Codecs"
      - "org.freedesktop.Platform.Locale"
      - "org.freedesktop.Platform"
      - "com.github.Eloston.UngoogledChromium"
      - "org.mozilla.firefox.Locale"
      - "org.mozilla.firefox"
      - "org.freedesktop.Sdk.Locale"
      - "com.github.xournalpp.xournalpp.Locale"
      - "com.belmoussaoui.Authenticator.Locale"
      - "org.kde.KStyle.Adwaita"
      - "org.kde.Platform"
      - "org.kde.Platform.Locale"

zfs_datasets_flatpak_apps:
      - "com.github.tchx84.Flatseal"
      - "com.github.eloston.ungoogledchromium"
      - "com.vscodium.codium"
      - "com.jgraph.drawio.desktop"
      - "com.discordapp.discord"
      - "com.github.xournalpp.xournalpp"
      - "us.zoom.zoom"
      - "com.axosoft.gitkraken"
      - "com.belmoussaoui.Authenticator"
      - "net.cozic.joplin_desktop"
      - "net.davidotek.pupgui2"



