[[swipe.commands]]
fingers = 3
left_up = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Overview"
right_up = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Overview"
up = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Walk Through Windows (Reverse)'"
left_down = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Overview"
right_down = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Overview"
down = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Walk Through Windows'"
left = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Switch One Desktop to the Right'"
right = "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut 'Switch One Desktop to the Left'"

[[swipe.commands]]
fingers = 4
left_up = "qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut 'next_layout'"
right_up = "qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut 'next_layout'"
up = "qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut 'move_window_to_upper_pos'"
left_down = "qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut 'next_layout'"
right_down = "qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut 'next_layout'"
down = "qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut 'move_window_to_bottom_pos'"
left = "qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut 'move_window_to_left_pos'"
right = "qdbus org.kde.kglobalaccel /component/bismuth org.kde.kglobalaccel.Component.invokeShortcut 'move_window_to_right_pos'"

[[pinch.commands]]
type = "CONTINUOUS"
in = "ydotool key ctrl+minus"
out = "ydotool key ctrl+plus"

[settings]
pinch.threshold = 0.13
rotate.threshold = 20
interact.type = "BOTH"

[settings.gesture_swipe]
threshold = 0.7
trigger_on_release = false